#!/bin/sh

set -e

while getopts 'E:D:' opt
do
	case "${opt}" in
	E) TEST_BIN="${OPTARG}" ;;
	D) TEST_DIR="${OPTARG}" ;;
	?) printf 'Unknown option: %s\n' "${opt}" && exit 1 ;;
	esac
done

if [ ! -x "${TEST_BIN}" ]
then
	printf '%s: Missing test binary\n' "$0"
	exit 1
fi

if [ -z "${TEST_DIR}" ]
then
	printf '%s: Missing test directory\n' "$0"
	exit 1
fi

export TEST_BIN
export TEST_ARCHIVE="${PWD}/archive.hny"
export HNY_PREFIX="${PWD}/HoneyTestPrefix"

shift $((OPTIND - 1))

if [ ! -f "${TEST_ARCHIVE}" ]
then
	archive_cpio() {
		printf '070707004021002167040755%.6o%.6o0000020000000000000000000000500000000000pkg/\0' "$1" "$2"
		printf '070707004021002170100755%.6o%.6o0000020000000000000000000001200000000046pkg/clean\0#!/bin/sh\necho "Test Archive - Clean"\n' "$1" "$2"
		printf '070707004021002170100755%.6o%.6o0000020000000000000000000001200000000046pkg/setup\0#!/bin/sh\necho "Test Archive - Setup"\n' "$1" "$2"
		printf '0707070000000000000000000000000000000000010000000000000000000001300000000000TRAILER!!!\0'
	}

	archive_cpio "`id -u`" "`id -g`" | xz -C crc32 --lzma2 > "${TEST_ARCHIVE}"
fi

for TEST in $@
do
	TEST_SCRIPT="${TEST_DIR}/${TEST}"
	EXPECTED_OUTPUT="${TEST_SCRIPT}.expected"

	if [ -f "${EXPECTED_OUTPUT}" ]
	then "${TEST_SCRIPT}" | diff - "${EXPECTED_OUTPUT}"
	else "${TEST_SCRIPT}"
	fi
done

