.PHONY: all clean
all:
$(OBJECTS)/hny:
	$(MKDIR) -p $@
$(OBJECTS)/hny/main.o: src/hny/main.c $(OBJECTS)/hny
	$(CC) $(CFLAGS) -c -o $@ $<
$(BINARIES)/hny: $(OBJECTS)/hny/main.o $(LIBRARIES)/libhny.so
	$(LD) $(LDFLAGS) $(HNYFLAGS) -o $@ $^
$(OBJECTS)/libhny:
	$(MKDIR) -p $@
$(OBJECTS)/libhny/hny_extraction.o: src/libhny/hny_extraction.c $(OBJECTS)/libhny
	$(CC) $(CFLAGS) -c -o $@ $<
$(OBJECTS)/libhny/hny_extraction_cpio.o: src/libhny/hny_extraction_cpio.c $(OBJECTS)/libhny
	$(CC) $(CFLAGS) -c -o $@ $<
$(OBJECTS)/libhny/hny_extraction_lzma2.o: src/libhny/hny_extraction_lzma2.c $(OBJECTS)/libhny
	$(CC) $(CFLAGS) -c -o $@ $<
$(OBJECTS)/libhny/hny_extraction_xz.o: src/libhny/hny_extraction_xz.c $(OBJECTS)/libhny
	$(CC) $(CFLAGS) -c -o $@ $<
$(OBJECTS)/libhny/hny_prefix.o: src/libhny/hny_prefix.c $(OBJECTS)/libhny
	$(CC) $(CFLAGS) -c -o $@ $<
$(OBJECTS)/libhny/hny_remove.o: src/libhny/hny_remove.c $(OBJECTS)/libhny
	$(CC) $(CFLAGS) -c -o $@ $<
$(OBJECTS)/libhny/hny_shift.o: src/libhny/hny_shift.c $(OBJECTS)/libhny
	$(CC) $(CFLAGS) -c -o $@ $<
$(OBJECTS)/libhny/hny_spawn.o: src/libhny/hny_spawn.c $(OBJECTS)/libhny
	$(CC) $(CFLAGS) -c -o $@ $<
$(OBJECTS)/libhny/hny_type.o: src/libhny/hny_type.c $(OBJECTS)/libhny
	$(CC) $(CFLAGS) -c -o $@ $<
$(LIBRARIES)/libhny.so: $(OBJECTS)/libhny/hny_extraction.o $(OBJECTS)/libhny/hny_extraction_cpio.o $(OBJECTS)/libhny/hny_extraction_lzma2.o $(OBJECTS)/libhny/hny_extraction_xz.o $(OBJECTS)/libhny/hny_prefix.o $(OBJECTS)/libhny/hny_remove.o $(OBJECTS)/libhny/hny_shift.o $(OBJECTS)/libhny/hny_spawn.o $(OBJECTS)/libhny/hny_type.o
	$(LD) $(LDFLAGS) $(LIBHNYFLAGS) -o $@ $^
all: $(BINARIES)/hny $(LIBRARIES)/libhny.so
clean:
	rm -rf $(BINARIES)/* $(LIBRARIES)/* $(OBJECTS)/*
